require 'faker'
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.destroy_all
Group.destroy_all
UserGroup.destroy_all
Event.destroy_all
Activity.destroy_all

mendel = User.create(name: "Mendel Stillerman", image: "003-man-1.svg", password: "123", username: "mendel")
chris = User.create(name: "Chris Yuan", image: "012-man-5.svg", password: "123", username: "chris")
aaron = User.create(name: "Aaron Smith", image: "009-cowboy.svg", password: "123", username: "aaron")
amy = User.create(name: "Amy Cen", image: "001-woman.svg", password: "123", username: "amy")
aniket = User.create(name: "Aniket Patel", image: "006-man-4.svg", password: "123", username: "aniket")
catherine = User.create(name: "Catherine", image: "030-woman-5.svg", password: "123", username: "catherine")
charlie = User.create(name: "Charlie Russo", image: "014-man-6.svg", password: "123", username: "charlie")
christian = User.create(name: "Christian Pinto", image: "033-boy.svg", password: "123", username: "christian")
david = User.create(name: "David Greenspan", image: "031-student.svg", password: "123", username: "david")
emi = User.create(name: "Emi Katsuta", image: "010-cowgirl.svg", password: "123", username: "emi")
kevin = User.create(name: "Kevin Dai", image: "029-man-14.svg", password: "123", username: "kevin")
sophia = User.create(name: "Sophia Song", image: "015-gymnast.svg", password: "123", username: "sophia")
stephen = User.create(name: "Stephen Brewer", image: "026-man-11.svg", password: "123", username: "stephen")
steven = User.create(name: "Steven Balasta", image: "021-man-8.svg", password: "123", username: "steven")
will = User.create(name: "Will Bainton", image: "017-hipster-1.svg", password: "123", username: "will")
mary = User.create(name: "Mary Crivelli", image: "034-girl.svg", password: "123", username: "mary")
gabe = User.create(name: "Gabe Vazquez", image: "015-gymnast.svg", password: "123", username: "gabe")
jaimie = User.create(name: "Jaimie Nguyen", image: "013-woman-2.svg", password: "123", username: "jaimie")
matt = User.create(name: "Matthew Masiello", image: "025-nerd.svg", password: "123", username: "matt")
dean = User.create(name: "Constantine Chutis", image: "005-man-3.svg", password: "123", username: "dean")
oscar = User.create(name: "Oscar Rios", image: "004-man-2.svg", password: "123", username: "oscar")
yana = User.create(name: "Yana Loginova", image: "035-woman-6.svg", password: "123", username: "yana")
nick = User.create(name: "Nicholas Machin", image: "019-man-7.svg", password: "123", username: "nick")

web = Group.create(name: "nyc-mhtn-web-051319", creator: charlie.name, description: "Flatiron School Web Dev Cohort aka Code Blooded")
avalon = Group.create(name: "Avalon", creator: gabe.name, description: "Laugh at people get mad.")
lunch = Group.create(name: "Lunch Squad", creator: aaron.name, description: "We actually take lunch.")
memes = Group.create(name: "code-blooded-memes", creator: kevin.name, description: "Copy & paste from Reddit.")
fun = Group.create(name: "zboard-game-cult", creator: david.name, description: "No instructors allowed :)")
smoke = Group.create(name: "Vape Gang", creator: dean.name, description: "Wanna go out?")
amigos = Group.create(name: "Three Amigos", creator: matt.name, description: "Holding it down since 051319.")
anime = Group.create(name: "Weeb Central", creator: kevin.name, description: "All things anime.")

UserGroup.create(user_id: mendel.id, group_id: web.id)
UserGroup.create(user_id: chris.id, group_id: web.id)
UserGroup.create(user_id: aaron.id, group_id: web.id)
UserGroup.create(user_id: amy.id, group_id: web.id)
UserGroup.create(user_id: aniket.id, group_id: web.id)
UserGroup.create(user_id: catherine.id, group_id: web.id)
UserGroup.create(user_id: charlie.id, group_id: web.id)
UserGroup.create(user_id: christian.id, group_id: web.id)
UserGroup.create(user_id: david.id, group_id: web.id)
UserGroup.create(user_id: emi.id, group_id: web.id)
UserGroup.create(user_id: kevin.id, group_id: web.id)
UserGroup.create(user_id: sophia.id, group_id: web.id)
UserGroup.create(user_id: stephen.id, group_id: web.id)
UserGroup.create(user_id: steven.id, group_id: web.id)
UserGroup.create(user_id: will.id, group_id: web.id)
UserGroup.create(user_id: mary.id, group_id: web.id)
UserGroup.create(user_id: gabe.id, group_id: web.id)
UserGroup.create(user_id: jaimie.id, group_id: web.id)
UserGroup.create(user_id: matt.id, group_id: web.id)
UserGroup.create(user_id: dean.id, group_id: web.id)
UserGroup.create(user_id: oscar.id, group_id: web.id)
UserGroup.create(user_id: yana.id, group_id: web.id)
UserGroup.create(user_id: nick.id, group_id: web.id)
UserGroup.create(user_id: gabe.id, group_id: avalon.id)
UserGroup.create(user_id: amy.id, group_id: avalon.id)
UserGroup.create(user_id: will.id, group_id: avalon.id)
UserGroup.create(user_id: kevin.id, group_id: avalon.id)
UserGroup.create(user_id: chris.id, group_id: avalon.id)
UserGroup.create(user_id: aaron.id, group_id: avalon.id)
UserGroup.create(user_id: aaron.id, group_id: lunch.id)
UserGroup.create(user_id: jaimie.id, group_id: lunch.id)
UserGroup.create(user_id: emi.id, group_id: lunch.id)
UserGroup.create(user_id: mary.id, group_id: lunch.id)
UserGroup.create(user_id: sophia.id, group_id: lunch.id)
UserGroup.create(user_id: yana.id, group_id: lunch.id)
UserGroup.create(user_id: kevin.id, group_id: memes.id)
UserGroup.create(user_id: jaimie.id, group_id: memes.id)
UserGroup.create(user_id: will.id, group_id: memes.id)
UserGroup.create(user_id: chris.id, group_id: memes.id)
UserGroup.create(user_id: stephen.id, group_id: memes.id)
UserGroup.create(user_id: amy.id, group_id: memes.id)
UserGroup.create(user_id: gabe.id, group_id: memes.id)
UserGroup.create(user_id: david.id, group_id: memes.id)
UserGroup.create(user_id: dean.id, group_id: memes.id)
UserGroup.create(user_id: dean.id, group_id: smoke.id)
UserGroup.create(user_id: stephen.id, group_id: smoke.id)
UserGroup.create(user_id: aniket.id, group_id: smoke.id)
UserGroup.create(user_id: will.id, group_id: smoke.id)
UserGroup.create(user_id: steven.id, group_id: amigos.id)
UserGroup.create(user_id: matt.id, group_id: amigos.id)
UserGroup.create(user_id: charlie.id, group_id: amigos.id)
UserGroup.create(user_id: kevin.id, group_id: anime.id)
UserGroup.create(user_id: steven.id, group_id: anime.id)
UserGroup.create(user_id: aaron.id, group_id: fun.id)
UserGroup.create(user_id: amy.id, group_id: fun.id)
UserGroup.create(user_id: gabe.id, group_id: fun.id)
UserGroup.create(user_id: kevin.id, group_id: fun.id)
UserGroup.create(user_id: chris.id, group_id: fun.id)
UserGroup.create(user_id: emi.id, group_id: fun.id)
UserGroup.create(user_id: mary.id, group_id: fun.id)
UserGroup.create(user_id: mendel.id, group_id: fun.id)
UserGroup.create(user_id: nick.id, group_id: fun.id)
UserGroup.create(user_id: will.id, group_id: fun.id)
UserGroup.create(user_id: stephen.id, group_id: fun.id)
UserGroup.create(user_id: david.id, group_id: fun.id)
UserGroup.create(user_id: christian.id, group_id: fun.id)
UserGroup.create(user_id: jaimie.id, group_id: fun.id)
UserGroup.create(user_id: sophia.id, group_id: fun.id)
UserGroup.create(user_id: aniket.id, group_id: fun.id)
UserGroup.create(user_id: dean.id, group_id: fun.id)
UserGroup.create(user_id: yana.id, group_id: fun.id)

activities = ['Coding', 'Basketball', 'Chilling', 'Drinking', 'Going to the Movies', 'Karaoke', 'Eat Food']


coding = Activity.create(title: 'Coding',location: 'Flatiron School', icon: "laptop")
ball = Activity.create(title: 'Basketball',location: 'Battery Park', icon: "basketball ball")
chill = Activity.create(title: 'Chilling',location: 'Flatiron School', icon: "coffee")
drink = Activity.create(title: 'Drinking',location: 'Flatiron School', icon: "beer")
movies = Activity.create(title: 'Going to the Movies',location: 'AMC Theater', icon: "coffee")
sing = Activity.create(title: 'Karaoke',location: 'Chinatown', icon: "beer")
eat = Activity.create(title: 'Eat Food',location: 'Around Flatiron School', icon: "utensils")
play = Activity.create(title: 'Play Avalon',location: 'Flatiron School', icon: "user secret")
vape = Activity.create(title: 'Smoke Sesh',location: 'Outside Flatiron School', icon: "cloud")


Event.create(group_id: web.id, activity_id: coding.id, name: 'Mod 4 Project Demos', time: '2019-07-31T14:30', creator: charlie.name)
Event.create(group_id: web.id, activity_id: coding.id, name: 'Redux', time: '2019-08-01T09:30', creator: steven.name)
Event.create(group_id: web.id, activity_id: coding.id, name: 'Mod 5!!!', time: '2019-08-05T09:10', creator: matt.name)
Event.create(group_id: avalon.id, activity_id: play.id, name: 'AVALON TIME', time: '2019-08-02T16:00', creator: gabe.name)
Event.create(group_id: lunch.id, activity_id: eat.id, name: 'Taking Lunch', time: '2019-08-01T12:00', creator: emi.name)
Event.create(group_id: memes.id, activity_id: chill.id, name: 'Meme Review', time: '2019-08-02T17:00', creator: kevin.name)
Event.create(group_id: fun.id, activity_id: drink.id, name: 'Community Happy Hour', time: '2019-08-02T16:00', creator: stephen.name)
Event.create(group_id: smoke.id, activity_id: vape.id, name: 'Go outside', time: '2019-07-31T15:30', creator: dean.name)
>>>>>>> d6469334a95179931b8663d2d848cea7379b97b2
